### ISSUE TITLE
Failed to go get package after bump controller-runtime to v0.10.1

### ISSUE THREAD

**Issue by ycyxuehan** [kubernetes-sigs/controller-runtime#1726]
尝试过使用go get获取过0.10.3/0.10.2/0.10.1三个版本的包，均无法正常工作，出现类似下方的错误：
```bash
# sigs.k8s.io/controller-runtime/pkg/log
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/deleg.go:79:12: undefined: logr.WithCallDepth
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/deleg.go:163:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/deleg.go:179:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/deleg.go:195:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/log.go:67:26: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to Log.Fulfill
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/log.go:82:41: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to NewDelegatingLogger
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/log.go:86:6: cannot use Log (type *DelegatingLogger) as type logr.Logger in assignment
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/log.go:88:13: assignment mismatch: 1 variable but logr.FromContext returns 2 values
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/null.go:30:5: cannot use NullLogger{} (type NullLogger) as type logr.Logger in assignment
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/null.go:49:2: cannot use log (type NullLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/log/null.go:49:2: too many errors
```

**Comment by ycyxuehan** [comment]
```bash
# sigs.k8s.io/controller-runtime/pkg/log
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/deleg.go:79:12: undefined: logr.WithCallDepth
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/deleg.go:163:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/deleg.go:179:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/deleg.go:195:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/log.go:67:26: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to Log.Fulfill
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/log.go:82:41: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to NewDelegatingLogger
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/log.go:86:6: cannot use Log (type *DelegatingLogger) as type logr.Logger in assignment
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/log.go:88:13: assignment mismatch: 1 variable but logr.FromContext returns 2 values
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/null.go:30:5: cannot use NullLogger{} (type NullLogger) as type logr.Logger in assignment
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/null.go:49:2: cannot use log (type NullLogger) as type logr.Logger in return argument
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/log/null.go:49:2: too many errors
```

**Comment by coderanger** [comment]
Hi there, unfortunately I don't think we have any Chinese speakers who work on controller-runtime. Could you post your question in English?

**Comment by coderanger** [comment]
Going off auto-translate it sounds like you're trying to install controller-runtime into a blank or otherwise non-Kubebuilder project. You'll have to match our dependencies and things can get a bit complex given how many deps Kubernetes itself pulls in. If you generate a project using Kubebuilder, we set up the dependencies in a known working way. In this case it appears you have the wrong version of logr.

**Comment by ycyxuehan** [comment]
> Going off auto-translate it sounds like you're trying to install controller-runtime into a blank or otherwise non-Kubebuilder project. You'll have to match our dependencies and things can get a bit complex given how many deps Kubernetes itself pulls in. If you generate a project using Kubebuilder, we set up the dependencies in a known working way. In this case it appears you have the wrong version of logr.

i am sorry, i will try to communicate in english.

my project is created at 2019, and it work good at kubernets 1.18, now I upgrade my kubernetes to 1.22, so i should update my project. and then i got this issue.
I follow the steps below:
- clean the go.mod file
- run `go mod tidy`
- update my codes
- run `make docker-build`
the error occurred

**Comment by coderanger** [comment]
Yeah unfortunately go's dependency analysis doesn't work well enough for our needs. What I would recommend is starting from our current default project layout test data https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/go.mod#L5-L12

**Comment by ycyxuehan** [comment]
> Yeah unfortunately go's dependency analysis doesn't work well enough for our needs. What I would recommend is starting from our current default project layout test data https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/go.mod#L5-L12

i have tried my code in go 1.15.2, it works!
this issue appear in go 1.17.3.

**Comment by FillZpp** [comment]
> unfortunately I don't think we have any Chinese speakers who work on controller-runtime

Actually we have, it's me 😆 

@ycyxuehan It seems all errors you got are caused by `"github.com/go-logr/logr"` dependency. Generally speaking, you have to update the dependencies in your `go.mod` to the version used in `controller-runtime@v0.10.1`'s `go.mod`.

/retitle Failed to go get package after bump controller-runtime to v0.10.1

**Comment by ycyxuehan** [comment]
> > unfortunately I don't think we have any Chinese speakers who work on controller-runtime
> 
> Actually we have, it's me 😆
> 
> @ycyxuehan It seems all errors you got are caused by `"github.com/go-logr/logr"` dependency. Generally speaking, you have to update the dependencies in your `go.mod` to the version used in `controller-runtime@v0.10.1`'s `go.mod`.
> 
> /retitle Failed to go get package after bump controller-runtime to v0.10.1

i tried v0.10.0~v0.10.3, all failed, the go version is 1.17.3.
how can i fix this execpt use old go.
