### ISSUE TITLE
setup-envtest does no longer works with go prior to 1.19

### ISSUE THREAD

**Issue by TeddyAndrieux** [kubernetes-sigs/controller-runtime#2537]
I don't know if it's on purpose or not but since the last changes on go dependencies for setup-envtest it can no longer be installed on go versions prior to 1.19

```console
$ docker run -it --rm golang:1.19 go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime v0.16.2
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231010022941-78b3ce63cf92
go: downloading github.com/go-logr/zapr v1.2.4
go: downloading github.com/spf13/afero v1.6.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-logr/logr v1.2.4
go: downloading go.uber.org/zap v1.26.0
go: downloading go.uber.org/multierr v1.10.0
go: downloading golang.org/x/text v0.12.0
$ docker run -it --rm golang:1.18 go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime v0.16.2
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231010022941-78b3ce63cf92
go: downloading github.com/go-logr/zapr v1.2.4
go: downloading github.com/spf13/afero v1.6.0
go: downloading go.uber.org/zap v1.26.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-logr/logr v1.2.4
go: downloading golang.org/x/text v0.12.0
go: downloading go.uber.org/multierr v1.10.0
# go.uber.org/multierr
pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
```

I know that 1.18 is EOL but still, it's sad to me.

Btw in the readme, it still mentioned that it requires go1.16+, so at least the readme needs to be updated

**Comment by troy0820** [comment]
/kind support 

Unfortunately, setupenv-test isn't tagged with the releases.  There are hashes that work with versions lower than v1.19 but I believe to be able to use the "latest" it tries to stay in parity with the go version controller-runtime uses.  

To support the lower versions while incrementing the controller-runtime go.mod with its dependencies can create a support matrix the dependencies may mismanage.  (e.g the `pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool` needs 1.19, etc)

To be able to use the setup-envtest at a lower version would require the hash to be used instead of latest, and doing that may not give you the tooling you need to do so.  


Updating the README to be in sync with the controller-runtime go.mod is a very valid point.
