### ISSUE TITLE
Workqueue metrics have wrong unit

### ISSUE THREAD

**Issue by dohnto** [kubernetes-sigs/controller-runtime#335]
Controller-runtime provides prometheus metrics - for example `workqueue_queue_latency_seconds` in seconds: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/client_go_adapter.go#L126

However client-go imlemented those metrics not as seconds but as microseconds (client-go=v10.0.0). See https://github.com/kubernetes/client-go/blob/v10.0.0/util/workqueue/metrics.go#L107 .

Recently there has been [a fix](https://github.com/kubernetes/client-go/commit/c270b352df14c6441431e4c008b12265f40118a9) in client-go library implementing those metrics with seconds sentatics. However, the [MetricsProvider interface](https://github.com/kubernetes/client-go/blob/c270b352df14c6441431e4c008b12265f40118a9/util/workqueue/metrics.go#L190) has changed and now the [reflectorMetricsProvider](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/client_go_adapter.go#L232) does not implement the interface:

```
vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go:201:55: cannot use workqueueMetricsProvider literal (type workqueueMetricsProvider) as type workqueue.MetricsProvider in argument to workqueue.SetProvider:
	workqueueMetricsProvider does not implement workqueue.MetricsProvider (missing NewDeprecatedAddsMetric method)
```

**Comment by DirectXMan12** [comment]
We'll handle that when we update to 1.14 dependencies, when it comes out, if nobody submits a PR before then, but we generally match semantics of the released version of Kubernetes.

**Comment by DirectXMan12** [comment]
fixed recently, IIRC

**Comment by yiqinguo** [comment]
When can solve this problem?

**Comment by LouisPlisso** [comment]
@DirectXMan12 I am able to reproduce in v0.4.0

can you please re-open or give us a solution/workaround?

**Comment by DirectXMan12** [comment]
@LouisPlisso can you please provide your `go.mod` file?

**Comment by LouisPlisso** [comment]
sure @DirectXMan12, here it is

```
(default) [louis.plissonneau@Louiss-MacBook-Pro:…/10gen/ops-manager-kubernetes] cat go.mod
module github.com/10gen/ops-manager-kubernetes

require (
        github.com/beorn7/perks v1.0.1 // indirect
        github.com/blang/semver v3.5.1+incompatible
        github.com/emicklei/go-restful v2.9.6+incompatible // indirect
        github.com/go-openapi/jsonreference v0.19.3 // indirect
        github.com/go-openapi/spec v0.19.4 // indirect
        github.com/google/uuid v1.1.1
        github.com/hashicorp/golang-lru v0.5.3 // indirect
        github.com/imdario/mergo v0.3.8
        github.com/json-iterator/go v1.1.8 // indirect
        github.com/pkg/errors v0.8.1
        github.com/prometheus/client_golang v0.9.4 // indirect
        github.com/prometheus/procfs v0.0.8 // indirect
        github.com/spf13/cast v1.3.0
        github.com/spf13/pflag v1.0.5 // indirect
        github.com/stretchr/testify v1.4.0
        github.com/xdg/stringprep v1.0.0
        go.uber.org/zap v1.10.0
        gopkg.in/yaml.v2 v2.2.7 // indirect
        k8s.io/api v0.0.0-20191114100237-2cd11237263f // 1.15.6
        k8s.io/apimachinery v0.0.0-20191004115701-31ade1b30762 // 1.15.6
        k8s.io/client-go v0.0.0-20191114101336-8cba805ad12d // 1.15.6
        k8s.io/code-generator v0.0.0-20190912054826-cd179ad6a269 // 1.15.6
        sigs.k8s.io/controller-runtime v0.4.0
)

go 1.13
(default) [louis.plissonneau@Louiss-MacBook-Pro:…/10gen/ops-manager-kubernetes] GOFLAGS="" go get -u=patch
# sigs.k8s.io/controller-runtime/pkg/metrics
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/metrics/workqueue.go:32:48: cannot use composite literal (type workqueueMetricsProvider) as type workqueue.MetricsProvider in argument to workqueue.SetProvider:
        workqueueMetricsProvider does not implement workqueue.MetricsProvider (missing NewDeprecatedAddsMetric method)
```

**Comment by LouisPlisso** [comment]
@DirectXMan12 as the error message is different that the original one for this issue, should I create a new issue?

**Comment by DirectXMan12** [comment]
v0.4.0 is intended for use with v1.16.0.  Please try with that.
