### ISSUE TITLE
Patch option error: client.FieldOwner does not implement 'SubResourcePatchOption'

### ISSUE THREAD

**Issue by ArenaSu** [kubernetes-sigs/controller-runtime#2204]
controller-runtime version
```
sigs.k8s.io/controller-runtime v0.14.1
```

Code below:
```
import sigs.k8s.io/controller-runtime/pkg/client
...
func EndReconcileWithNegativeCondition(ctx context.Context, r client.StatusClient, workload ConditionedObject,
	condition ...condition.Condition) error {
	if len(condition) == 0 {
		return nil
	}
	workloadPatch := client.MergeFrom(workload.DeepCopyObject().(client.Object))
	conditionIsChanged := IsConditionChanged(condition, workload)
	workload.SetConditions(condition...)
	if err := r.Status().Patch(ctx, workload, workloadPatch, client.FieldOwner(workload.GetUID())); err != nil {
		return errors.Wrap(err, ErrUpdateStatus)
	}
	if conditionIsChanged {
		// if any condition is changed, patching status can trigger requeue the resource and we should return nil to
		// avoid requeue it again
		return nil
	}
	// if no condition is changed, patching status can not trigger requeue, so we must return an error to
	// requeue the resource
	return errors.Errorf(ErrReconcileErrInCondition, condition[0].Type, condition[0].Message)
}
```

Goland error messge below:

```
Cannot use 'client.FieldOwner(workload.GetUID())' (type client.FieldOwner) as the type SubResourcePatchOption Type does not implement 'SubResourcePatchOption' as some methods are missing: ApplyToSubResourcePatch(*SubResourcePatchOptions)
```

**Comment by alvaroaleman** [comment]
Feel free to submit a fix

**Comment by alculquicondor** [comment]
This was broken by #2072
I can work on a fix tomorrow.

**Comment by alculquicondor** [comment]
If we provide a fix, how fast can we produce a release?

**Comment by alculquicondor** [comment]
oh, this was already fixed by #2115

/close
