### ISSUE TITLE
Does not compile with apimachinery 1.31

### ISSUE THREAD

**Issue by cagataygurturk** [kubernetes-sigs/controller-runtime#2927]
It seems the changes introduced on https://github.com/kubernetes/kubernetes/pull/121970/files#diff-723a06b5a60646d0e6eeaf63b66f2672b579c72f7008c9ab8529446f20484014R39 broke controller-runtime.

````
# sigs.k8s.io/controller-runtime/pkg/internal/controller
/Users/cguertuerk/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:103:9: not enough arguments in call to fn
	have (interface{})
	want (context.Context, interface{})
# sigs.k8s.io/controller-runtime/pkg/webhook/admission
/Users/cguertuerk/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/webhook/admission/webhook.go:158:9: not enough arguments in call to fn
	have (interface{})
	want (context.Context, interface{})
````

**Comment by cagataygurturk** [comment]
> Interesting, mostly the same answers from #2925 apply
> 
> (cc @dims fyi)

Thanks, I figured the next release will bring 1.31 compatibility and I see that the offending code above is waiting to be released. Let me close the issue.

**Comment by sbueringer** [comment]
@cagataygurturk Was this already changed back? We didn't change anything in controller-runtime and the controller-runtime main branch doesn't have an issue with k8s.io/apimachinery 0.31.0

**Comment by cagataygurturk** [comment]
@sbueringer 

I've seen that https://github.com/kubernetes-sigs/controller-runtime/pull/2798 made the necessary changes to cover the new function signature in 1.31. Once the changes in this PR is released, I guess the issue will be fixed. 

I believe this issue can be closed because of that.

**Comment by sbueringer** [comment]
Sounds good. Thx for clarifying!

/close
