### ISSUE TITLE
0.14.1 regression: cannot use server-side apply

### ISSUE THREAD

**Issue by Gchbg** [kubernetes-sigs/controller-runtime#2125]
Hi,

After upgrading from 0.13.1 to 0.14.1, I can no longer use server-side apply.

In 0.13.1 I used to be able to do this:
`err = r.Status().Patch(ctx, obj, client.Apply, client.FieldOwner("whatever"), client.ForceOwnership)`

In 0.14.1 this results in:
```
Cannot use 'client.FieldOwner("whatever")' (type client.FieldOwner) as the type SubResourcePatchOptionType does not implement 'SubResourcePatchOption' as some methods are missing:ApplyToSubResourcePatch(*SubResourcePatchOptions)
Cannot use 'client.ForceOwnership' (type forceOwnership) as the type SubResourcePatchOptionType does not implement 'SubResourcePatchOption' as some methods are missing:ApplyToSubResourcePatch(*SubResourcePatchOptions)
```

I assume this is due to the breaking change introduced in #2072. It seems that client.FieldOwner and client.ForceOwnership were not updated to use the new SubResourcePatchOption interface instead of the existing PatchOption interface.

If this was intended, I would appreciate any insight about what the line of code should look like in 0.14.1.

Thanks!

**Comment by alvaroaleman** [comment]
Fixes in the latest 0.14.3 release.

**Comment by Gchbg** [comment]
> Fixes in the latest 0.14.3 release.

Unfortunately the fix seems incomplete. ForceOwnership is still missing the ApplyToSubResourcePatch method.

**Comment by alvaroaleman** [comment]
@Gchbg please feel free to submit a fix
