### PR TITLE
 📖Update go version in setupenv-test README. Update release-notes link in RELEASE

### LINKED ISSUE #2537: setup-envtest does no longer works with go prior to 1.19
I don't know if it's on purpose or not but since the last changes on go dependencies for setup-envtest it can no longer be installed on go versions prior to 1.19

```console
$ docker run -it --rm golang:1.19 go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime v0.16.2
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231010022941-78b3ce63cf92
go: downloading github.com/go-logr/zapr v1.2.4
go: downloading github.com/spf13/afero v1.6.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-logr/logr v1.2.4
go: downloading go.uber.org/zap v1.26.0
go: downloading go.uber.org/multierr v1.10.0
go: downloading golang.org/x/text v0.12.0
$ docker run -it --rm golang:1.18 go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime v0.16.2
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20231010022941-78b3ce63cf92
go: downloading github.com/go-logr/zapr v1.2.4
go: downloading github.com/spf13/afero v1.6.0
go: downloading go.uber.org/zap v1.26.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/go-logr/logr v1.2.4
go: downloading golang.org/x/text v0.12.0
go: downloading go.uber.org/multierr v1.10.0
# go.uber.org/multierr
pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
```

I know that 1.18 is EOL but still, it's sad to me.

Btw in the readme, it still mentioned that it requires go1.16+, so at least the readme needs to be updated

### PR DESCRIPTION
**Pull request by troy0820**
- [x] Update go version on setupenv-test README to show what version is necessary to utilize the tool 
```bash
pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
```

Using `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest` with go versions < 1.19 will complain that this can not be installed due to the above dependency needing 1.19.  To still be able to use latest, updating the documentation to show that 1.19 is needed and to use this tool with older versions of go, commit hashes from older versions can be used as setupenv-test does not have tags included with the releases. 

Resolves #2537 
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/2526

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
Thanks!
