### ISSUE TITLE
Controller-runtime does not compile with client-go 1.31 with version v0.18.5

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#2925]
Reproducer:

`main.go`:
```
package main

import (
        _ "k8s.io/client-go"
        _ "sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func main() {
}
```

`go.mod`:
```
module test

go 1.22.6

require sigs.k8s.io/controller-runtime v0.18.5

require k8s.io/client-go v0.31.0
```

Gives:
```
$ go build .
# sigs.k8s.io/controller-runtime/pkg/client/fake
/home/john/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/client/fake/client.go:858:29: cannot use c.tracker (variable of type versionedTracker) as "k8s.io/client-go/testing".ObjectTracker value in argument to dryPatch: versionedTracker does not implement "k8s.io/client-go/testing".ObjectTracker (wrong type for method Create)
                have Create("k8s.io/apimachinery/pkg/runtime/schema".GroupVersionResource, "k8s.io/apimachinery/pkg/runtime".Object, string) error
                want Create("k8s.io/apimachinery/pkg/runtime/schema".GroupVersionResource, "k8s.io/apimachinery/pkg/runtime".Object, string, ..."k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
/home/john/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/client/fake/client.go:872:37: cannot use c.tracker (variable of type versionedTracker) as "k8s.io/client-go/testing".ObjectTracker value in argument to testing.ObjectReaction: versionedTracker does not implement "k8s.io/client-go/testing".ObjectTracker (wrong type for method Create)
                have Create("k8s.io/apimachinery/pkg/runtime/schema".GroupVersionResource, "k8s.io/apimachinery/pkg/runtime".Object, string) error
                want Create("k8s.io/apimachinery/pkg/runtime/schema".GroupVersionResource, "k8s.io/apimachinery/pkg/runtime".Object, string, ..."k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions) error
```

**Comment by howardjohn** [comment]
Broken by https://github.com/kubernetes/kubernetes/pull/125560

**Comment by howardjohn** [comment]
In the past sometimes we have done tricks to support both versions concurrently. I don't see how we can do it in this case

**Comment by dims** [comment]
cc @jpbetz @liggitt

**Comment by danielvegamyhre** [comment]
I am impacted by this as well.

**Comment by sbueringer** [comment]
While this is not great, it is not something that we guarantee to support, see: https://github.com/kubernetes-sigs/controller-runtime#compatibility

**Comment by jpbetz** [comment]
Can anyone impacted verify that if they upgrade client-go into the supported skew range that the problem is resolved?

**Comment by howardjohn** [comment]
Ah I looked for a newer CR release but didn't see it since where I was looking filtered out 0.19 due to the -beta suffix. At least in my example reproducer that does seem to compile.

**Comment by sbueringer** [comment]
Ah, makes sense! Yup 0.19 would be the corret release for k8s.io/* 1.31.0

I think we'll release it soon. Last thing we want to get done before is this one: https://github.com/kubernetes-sigs/controller-runtime/pull/2901 (at least as far as I'm aware)

**Comment by sbueringer** [comment]
Related Slack thread: https://kubernetes.slack.com/archives/CHGFYJVAN/p1723581467467729

**Comment by dims** [comment]
> I think we'll release it soon. 

thanks @sbueringer !

**Comment by davidkarlsen** [comment]
Hm, when I use 0.19, I get this problem: https://github.com/davidkarlsen/flyway-operator/actions/runs/10406586858/job/28819954478

**Comment by liggitt** [comment]
> Hm, when I use 0.19, I get this problem: https://github.com/davidkarlsen/flyway-operator/actions/runs/10406586858/job/28819954478

that CI run is still referencing 0.29.0 versions of some kubernetes libraries, I think there's a version mismatch there or they have not all been bumped to 0.31.0 consistently

```
go: downloading k8s.io/apiextensions-apiserver v0.29.0
go: downloading k8s.io/apimachinery v0.29.0
```

**Comment by davidkarlsen** [comment]
I figured out it was my controller-gen tooling being outdated.

**Comment by troy0820** [comment]
/retitle Controller-runtime does not compile with client-go 1.31 with version v0.18.5

Do we still need this open? I believe we released v0.19.0 and it works along with the table @sbueringer created on the README.

**Comment by howardjohn** [comment]
From my POV good to close
